"""initial_schema

Revision ID: 147a729ba08a
Revises: 
Create Date: 2026-06-16 17:04:02.476442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '147a729ba08a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_scrape', sa.DateTime(), nullable=True),
    sa.Column('last_scrape_status', sa.String(), nullable=True),
    sa.Column('commits_added', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_status')
    # ### end Alembic commands ###
